export const productCard = [
	{
	id: 0,
	name: 'Кольцо гвоздь',
	manufacturer: 'Cartier',
	price: '200 000₽',
	url: '../public/cartier.png',
	},
	{
		id: 1,
		name: 'Кольцо гвоздь',
		manufacturer: 'Cartier',
		price: '200 000₽',
		url: '../public/cartier.png',
	},
	{
	id: 2,
	name: 'Кольцо гвоздь',
	manufacturer: 'Cartier',
	price: '200 000₽',
	url: '../public/cartier.png',
	},
	{
		id: 3,
		name: 'Кольцо гвоздь',
		manufacturer: 'Cartier',
		price: '200 000₽',
		url: '../public/cartier.png',
	},
	{
		id: 4,
		name: 'Кольцо гвоздь',
		manufacturer: 'Cartier',
		price: '200 000₽',
		url: '../public/cartier.png',
	},
	{
		id: 0,
		name: 'Кольцо гвоздь',
		manufacturer: 'Cartier',
		price: '200 000₽',
		url: '../public/cartier.png',
		},
		{
			id: 1,
			name: 'Кольцо гвоздь',
			manufacturer: 'Cartier',
			price: '200 000₽',
			url: '../public/cartier.png',
		},
		{
		id: 2,
		name: 'Кольцо гвоздь',
		manufacturer: 'Cartier',
		price: '200 000₽',
		url: '../public/cartier.png',
		},
		{
			id: 3,
			name: 'Кольцо гвоздь',
			manufacturer: 'Cartier',
			price: '200 000₽',
			url: '../public/cartier.png',
		},
		{
			id: 4,
			name: 'Кольцо гвоздь',
			manufacturer: 'Cartier',
			price: '200 000₽',
			url: '../public/cartier.png',
		},
]
